"""Init

Revision ID: 729700c41ab8
Revises: 
Create Date: 2023-03-14 13:02:24.571169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729700c41ab8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=225), nullable=False),
    sa.Column('artist', sa.String(length=225), nullable=False),
    sa.Column('album', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('genre', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###
